import logging
import pandas as pd
from pathlib import Path
from src.evaluation.corners_calibration import CornerCalibrationEvaluator

# Configure logging to show info
logging.basicConfig(level=logging.INFO)

def verify():
    # Point to the new logs generated by backfill
    log_dir = Path("data/temp_backfill_logs")
    
    print(f"Verifying calibration on logs in {log_dir}...")
    
    evaluator = CornerCalibrationEvaluator(log_dir=log_dir)
    result = evaluator.evaluate()
    
    if result.is_empty:
        print("No results found!")
        return

    # Print relevant columns for the target leagues
    df = result.metrics_df
    target_leagues = ['PD', 'SA', 'BL1', 'PL']
    subset = df[df['league'].isin(target_leagues)]
    
    print("\n--- Calibration Results (Target Leagues) ---")
    print(subset[['league', 'sample_size', 'ece', 'status', 'calibration_gap']].to_string())
    
    # Check if any are still EXCLUDE
    if (subset['status'] == 'EXCLUDE').any():
        print("\nFAILURE: Some leagues are still EXCLUDE.")
    else:
        print("\nSUCCESS: All target leagues are ELIGIBLE/NEUTRAL/BOOST.")

if __name__ == "__main__":
    verify()
