"""
Historical Calibration Error (HCE) Penalty.

Penalizes predictions in buckets where historical calibration was poor.
Uses pessimistic default and time decay.
"""
import math
from typing import Dict, Tuple, Optional


# Precomputed ECE per (league, market, bucket)
# Generated by scripts/populate_ece_buckets.py from 365 days of data
ECE_BUCKETS: Dict[Tuple[str, str, str], float] = {
    # BL1 (Bundesliga)
    ('BL1', 'btts_no', '0.50-0.60'): 0.0607,
    ('BL1', 'btts_yes', '0.50-0.60'): 0.0013,
    ('BL1', 'btts_yes', '0.60-0.70'): 0.0339,
    ('BL1', 'corn_o75', '0.50-0.60'): 0.1727,
    ('BL1', 'corn_o75', '0.60-0.70'): 0.0753,
    ('BL1', 'corn_o75', '0.70-0.80'): 0.049,
    ('BL1', 'corn_o75', '0.80-0.90'): 0.1667,
    ('BL1', 'corn_u11', '0.50-0.60'): 0.0703,
    ('BL1', 'corn_u11', '0.60-0.70'): 0.0207,
    ('BL1', 'corn_u11', '0.70-0.80'): 0.0319,
    ('BL1', 'corn_u11', '0.80-0.90'): 0.0143,
    ('BL1', 'goals_o25', '0.50-0.60'): 0.031,
    ('BL1', 'goals_o25', '0.60-0.70'): 0.0513,
    ('BL1', 'goals_o25', '0.70-0.80'): 0.1199,
    ('BL1', 'goals_u25', '0.50-0.60'): 0.0183,
    # FL1 (Ligue 1)
    ('FL1', 'btts_no', '0.50-0.60'): 0.0542,
    ('FL1', 'btts_yes', '0.50-0.60'): 0.0142,
    ('FL1', 'corn_o75', '0.50-0.60'): 0.1364,
    ('FL1', 'corn_o75', '0.60-0.70'): 0.1386,
    ('FL1', 'corn_o75', '0.70-0.80'): 0.0482,
    ('FL1', 'corn_o75', '0.80-0.90'): 0.1333,
    ('FL1', 'corn_u11', '0.50-0.60'): 0.121,
    ('FL1', 'corn_u11', '0.60-0.70'): 0.0556,
    ('FL1', 'corn_u11', '0.70-0.80'): 0.0126,
    ('FL1', 'corn_u11', '0.80-0.90'): 0.0056,
    ('FL1', 'goals_o25', '0.50-0.60'): 0.0003,
    ('FL1', 'goals_o25', '0.60-0.70'): 0.1523,
    ('FL1', 'goals_u25', '0.50-0.60'): 0.0736,
    ('FL1', 'goals_u25', '0.60-0.70'): 0.0293,
    # PD (La Liga)
    ('PD', 'btts_no', '0.50-0.60'): 0.0467,
    ('PD', 'btts_yes', '0.50-0.60'): 0.027,
    ('PD', 'corn_o75', '0.50-0.60'): 0.0603,
    ('PD', 'corn_o75', '0.60-0.70'): 0.0417,
    ('PD', 'corn_o75', '0.70-0.80'): 0.0861,
    ('PD', 'corn_o75', '0.80-0.90'): 0.075,
    ('PD', 'corn_u11', '0.50-0.60'): 0.2308,
    ('PD', 'corn_u11', '0.60-0.70'): 0.0801,
    ('PD', 'corn_u11', '0.70-0.80'): 0.0021,
    ('PD', 'corn_u11', '0.80-0.90'): 0.1232,
    ('PD', 'goals_o25', '0.50-0.60'): 0.0047,
    ('PD', 'goals_o25', '0.60-0.70'): 0.0748,
    ('PD', 'goals_u25', '0.50-0.60'): 0.0013,
    ('PD', 'goals_u25', '0.60-0.70'): 0.0325,
    # PL (Premier League)
    ('PL', 'btts_no', '0.50-0.60'): 0.0723,
    ('PL', 'btts_yes', '0.50-0.60'): 0.0142,
    ('PL', 'corn_o75', '0.50-0.60'): 0.1381,
    ('PL', 'corn_o75', '0.60-0.70'): 0.1111,
    ('PL', 'corn_o75', '0.70-0.80'): 0.0554,
    ('PL', 'corn_o75', '0.80-0.90'): 0.0564,
    ('PL', 'corn_u11', '0.50-0.60'): 0.1744,
    ('PL', 'corn_u11', '0.60-0.70'): 0.1155,
    ('PL', 'corn_u11', '0.70-0.80'): 0.0318,
    ('PL', 'goals_o25', '0.50-0.60'): 0.0885,
    ('PL', 'goals_o25', '0.60-0.70'): 0.1735,
    ('PL', 'goals_u25', '0.50-0.60'): 0.0026,
    ('PL', 'goals_u25', '0.60-0.70'): 0.2705,
    # SA (Serie A)
    ('SA', 'btts_no', '0.50-0.60'): 0.0417,
    ('SA', 'btts_yes', '0.50-0.60'): 0.0537,
    ('SA', 'corn_o75', '0.50-0.60'): 0.0698,
    ('SA', 'corn_o75', '0.60-0.70'): 0.0051,
    ('SA', 'corn_o75', '0.70-0.80'): 0.1225,
    ('SA', 'corn_o75', '0.80-0.90'): 0.0593,
    ('SA', 'corn_u11', '0.50-0.60'): 0.2033,
    ('SA', 'corn_u11', '0.60-0.70'): 0.1701,
    ('SA', 'corn_u11', '0.70-0.80'): 0.1033,
    ('SA', 'goals_o25', '0.50-0.60'): 0.0931,
    ('SA', 'goals_u25', '0.50-0.60'): 0.0336,
    ('SA', 'goals_u25', '0.60-0.70'): 0.1123,
}


# Track when ECE was last updated
ECE_LAST_UPDATED: Dict[Tuple[str, str, str], int] = {}


def get_bucket(prob: float) -> str:
    """Get probability bucket string."""
    if prob < 0.50:
        return '0.00-0.50'
    elif prob < 0.60:
        return '0.50-0.60'
    elif prob < 0.70:
        return '0.60-0.70'
    elif prob < 0.80:
        return '0.70-0.80'
    elif prob < 0.90:
        return '0.80-0.90'
    else:
        return '0.90-1.00'


def calculate_hce_penalty(
    league: str,
    market: str,
    prob: float,
    days_since_update: int = 0,
    k: float = 5.0
) -> float:
    """
    Calculate Historical Calibration Error penalty.
    
    Args:
        league: League code
        market: Market identifier
        prob: Predicted probability
        days_since_update: Days since ECE was last computed
        k: Penalty scaling factor
        
    Returns:
        HCE penalty ∈ [0, 1] where higher = better calibration
    """
    bucket = get_bucket(prob)
    
    # Get ECE for this bucket, default to pessimistic 0.10
    ece = ECE_BUCKETS.get((league, market, bucket), 0.10)
    
    # Apply time decay: old calibration data lies
    if days_since_update > 0:
        ece *= math.exp(-days_since_update / 180)
    
    # Convert ECE to penalty: higher ECE = lower score
    penalty = math.exp(-ece * k)
    
    return max(0.0, min(penalty, 1.0))


def update_ece_bucket(
    league: str,
    market: str,
    bucket: str,
    ece: float
) -> None:
    """Update ECE for a specific bucket."""
    ECE_BUCKETS[(league, market, bucket)] = ece
    ECE_LAST_UPDATED[(league, market, bucket)] = 0
